scala_library(
    name = 'mysql',
    dependencies = [
        '3rdparty/jvm/com/twitter/finatra-http',
        '3rdparty/jvm/mysql',
        'beehave-app/src/main/scala/com/beehave/api/util',
    ],
    sources=globs('*.scala')
)
